program Robber;

uses
  Vcl.Forms,
  fMain in 'fMain.pas' {frmMain},
  DLLHijack in 'DLLHijack.pas',
  Vcl.Themes,
  Vcl.Styles,
  fAbout in 'fAbout.pas' {frmAbout},
  DigitalSignature in 'DigitalSignature.pas',
  gmap in 'PEParser\gmap.pas',
  grbtree in 'PEParser\grbtree.pas',
  NullStream in 'PEParser\NullStream.pas',
  PE.Build.Common in 'PEParser\PE.Build.Common.pas',
  PE.Build.Export in 'PEParser\PE.Build.Export.pas',
  PE.Build.Import in 'PEParser\PE.Build.Import.pas',
  PE.Build in 'PEParser\PE.Build.pas',
  PE.Build.Relocs in 'PEParser\PE.Build.Relocs.pas',
  PE.Build.Resource in 'PEParser\PE.Build.Resource.pas',
  PE.COFF in 'PEParser\PE.COFF.pas',
  PE.COFF.Types in 'PEParser\PE.COFF.Types.pas',
  PE.Common in 'PEParser\PE.Common.pas',
  PE.DataDirectories in 'PEParser\PE.DataDirectories.pas',
  PE.ExecutableLoader in 'PEParser\PE.ExecutableLoader.pas',
  PE.ExportSym in 'PEParser\PE.ExportSym.pas',
  PE.FileHeaderToStr in 'PEParser\PE.FileHeaderToStr.pas',
  PE.Headers in 'PEParser\PE.Headers.pas',
  PE.ID in 'PEParser\PE.ID.pas',
  PE.Image.Defaults in 'PEParser\PE.Image.Defaults.pas',
  PE.Image in 'PEParser\PE.Image.pas',
  PE.Image.Saving in 'PEParser\PE.Image.Saving.pas',
  PE.Image.x86 in 'PEParser\PE.Image.x86.pas',
  PE.Imports.Func in 'PEParser\PE.Imports.Func.pas',
  PE.Imports.Lib in 'PEParser\PE.Imports.Lib.pas',
  PE.Imports in 'PEParser\PE.Imports.pas',
  PE.MemoryStream in 'PEParser\PE.MemoryStream.pas',
  PE.Msg in 'PEParser\PE.Msg.pas',
  PE.Parser.Export in 'PEParser\PE.Parser.Export.pas',
  PE.Parser.Headers in 'PEParser\PE.Parser.Headers.pas',
  PE.Parser.Import in 'PEParser\PE.Parser.Import.pas',
  PE.Parser.ImportDelayed in 'PEParser\PE.Parser.ImportDelayed.pas',
  PE.Parser.PData in 'PEParser\PE.Parser.PData.pas',
  PE.Parser.Relocs in 'PEParser\PE.Parser.Relocs.pas',
  PE.Parser.Resources in 'PEParser\PE.Parser.Resources.pas',
  PE.Parser.TLS in 'PEParser\PE.Parser.TLS.pas',
  PE.ParserCallbacks in 'PEParser\PE.ParserCallbacks.pas',
  PE.ProcessModuleStream in 'PEParser\PE.ProcessModuleStream.pas',
  PE.Resources.Extract in 'PEParser\PE.Resources.Extract.pas',
  PE.Resources in 'PEParser\PE.Resources.pas',
  PE.Resources.VersionInfo in 'PEParser\PE.Resources.VersionInfo.pas',
  PE.Resources.Windows.Bitmap in 'PEParser\PE.Resources.Windows.Bitmap.pas',
  PE.Resources.Windows in 'PEParser\PE.Resources.Windows.pas',
  PE.Resources.Windows.Strings in 'PEParser\PE.Resources.Windows.Strings.pas',
  PE.RTTI in 'PEParser\PE.RTTI.pas',
  PE.Search in 'PEParser\PE.Search.pas',
  PE.Section in 'PEParser\PE.Section.pas',
  PE.Sections in 'PEParser\PE.Sections.pas',
  PE.TLS in 'PEParser\PE.TLS.pas',
  PE.Types.Directories in 'PEParser\PE.Types.Directories.pas',
  PE.Types.DOSHeader in 'PEParser\PE.Types.DOSHeader.pas',
  PE.Types.Export in 'PEParser\PE.Types.Export.pas',
  PE.Types.FileHeader in 'PEParser\PE.Types.FileHeader.pas',
  PE.Types.Imports in 'PEParser\PE.Types.Imports.pas',
  PE.Types.ImportsDelayed in 'PEParser\PE.Types.ImportsDelayed.pas',
  PE.Types.NTHeaders in 'PEParser\PE.Types.NTHeaders.pas',
  PE.Types.OptionalHeader in 'PEParser\PE.Types.OptionalHeader.pas',
  PE.Types in 'PEParser\PE.Types.pas',
  PE.Types.Relocations in 'PEParser\PE.Types.Relocations.pas',
  PE.Types.Resources in 'PEParser\PE.Types.Resources.pas',
  PE.Types.Sections in 'PEParser\PE.Types.Sections.pas',
  PE.Types.TLS in 'PEParser\PE.Types.TLS.pas',
  PE.Utils in 'PEParser\PE.Utils.pas',
  WinHelper in 'PEParser\WinHelper.pas';

{$R *.res}

begin
  //ReportMemoryLeaksOnShutdown:= True;
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('TabletDark');
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
